### PR TITLE
Show error when project with same name exist

### LINKED ISSUE #13: Show error, when a project as the same name already exit
issue
when creating a project, the same name as the project that already exists, it just overwrites the existing project

what you need to do
show an error if a project already exists and don't execute the command that creates the project(exit)

### PR DESCRIPTION
**Pull request by judicaelandria**
fixes #13 

exit the cmd if the project already exists and show a message: "project with the same name already exists" in red color

### CODE REVIEW

**Comment by saurabhdaware** [comment]
oh or wait. I can review this after merging the other PR so the commits will be removed from this PR. I will merge the other PR by tomorrow

**Comment by judicaelandria** [comment]
will merge this in main, tomorrow

**Comment by judicaelandria** [comment]
> oh or wait. I can review this after merging the other PR so the commits will be removed from this PR. I will merge the other PR by tomorrow

**Comment by judicaelandria** [comment]
> This also has code from the other PR. I think you will have to create a new branch from `judicaelandria:main` and copy paste changes there.

already did it, you can review and merge it

**Review by saurabhdaware — APPROVED** [review]
Looks great! Thank you so much again :D :partying_face:

**Comment by judicaelandria** [comment]
I'm happy to help! 😁

**Pull request merged**
